image: node:8.11.3

stages:
  - ver
  - tests
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-2
  STAGING_BUCKET_NAME: leaderboard-staging
  PRODUCTION_BUCKET_NAME: leaderboard-app

ver:
  stage: ver
  script:
    - node --version
    - whoami

build_staging:
  stage: build
  script:
    - npm cache verify
    - rm -rf node-modules
    - npm install
    - npm run build-staging
    - cp -a ./dist/. ./dist_staging
    - ls -a
  artifacts:
    paths:
      - dist_staging/
  only:
    - master

build_production:
  stage: build
  script:
    - npm cache verify
    - rm -rf node-modules
    - npm install
    - npm run build-prod
    - cp -a ./dist/. ./dist_production
    - ls -a
  artifacts:
    paths:
      - dist_production/
  only:
    - master

run_tests:
  stage: tests
  script:
    - echo "Add tests later"

deploy_staging:
  image: "python:latest"
  stage: deploy
  dependencies:
    - build_staging
  before_script:
    - pip install awscli
  script:
    - aws s3 cp ./dist_staging s3://${STAGING_BUCKET_NAME}/ --recursive
  environment:
    name: staging
  only:
    - master

deploy_production:
  image: "python:latest"
  stage: deploy
  dependencies:
    - build_production
  before_script:
    - pip install awscli
  script:
    - aws s3 cp ./dist_production s3://${STAGING_BUCKET_NAME}/ --recursive
  environment:
    name: staging
  only:
    - master